---
title: "Swiftkey Data Exploration"
author: "Bastiaan Quast"
date: "Monday, November 10, 2014"
output:
  html_document:
    keep_md: yes
---

# Abstract
This report analyses some of the basic features of the Swiftkey data.


# Data
The dataset consist of ...

Full instructions for importing the data can be found in the [CodeBook](https://github.com/bquast/Data-Science-Capstone/blob/master/CodeBook.md) of the [GitHub repository](https://github.com/bquast/Data-Science-Capstone).

# Basic Statistics

```{r}
load("en_US.RData")
```

```{r}
length(blogs)
length(news)
length(twitter)
```

```{r}
library(stringi)
library(ggplot2)
```

```{r}
stri_stats_general( blogs )
stri_stats_general( news )
stri_stats_general( twitter )
```

# Textual Analysis
Count the words, give a summary and a distribution
```{r}
words_blogs   <- stri_count_words(blogs)
summary( words_blogs )
qplot(   words_blogs )
```

```{r}
words_news    <- stri_count_words(news)
summary( words_news )
qplot(   words_news )
```

```{r}
words_twitter <- stri_count_words(twitter)
summary( words_twitter )
qplot(   words_twitter )
```